### ISSUE TITLE
Support editing the dashboard online

### ISSUE THREAD

**Issue by breezewish** [kennytm/grafana-export#22]
Sometimes people may want to adjust Y axis, or decimals, which requires editing the dashboard. Now this cannot be done since:

- In Viz UI, edit is not possible
- Even after importing the Dashboard to a local instance, edit is not possible as well (maybe because it is a snapshot).

**Comment by breezewish** [comment]
Looks like this is resolved now?

**Comment by kennytm** [comment]
Yes for 6.1.6. A bit buggy for dashboards exported from 7.1.5 but let's not care about that for now.
